---
- name: GoAccess | GPG Key
  apt_key:
    url: https://deb.goaccess.io/gnugpg.key
- name: GoAccess | repository
  apt_repository:
    repo: deb https://deb.goaccess.io/ {{ ansible_distribution_release }} main
    state: present
- name: GoAccess | Install
  apt:
    name:
      - goaccess
      - libncursesw5-dev
      - libgeoip-dev
      - libmaxminddb-dev
      - libssl-dev
    state: present
- name: GoAccess | Report cron
  become: no
  cron:
    name: goaccess report
    special_time: hourly
    job: "goaccess {{ root_path }}/var/log/access.log -o {{ root_path }}/public/report.html --log-format='%h %^[%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %T' --time-format=%T  --date-format='%d/%b/%Y'"
